"""
PaymentMethod (tokenized card, never a raw PAN) and PaymentIntent
(the core object tracking a charge through its lifecycle) models.
"""

import enum
import uuid

from sqlalchemy import Column, String, Integer, DateTime, Enum, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class PaymentMethodType(str, enum.Enum):
    CARD = "card"


class CardBrand(str, enum.Enum):
    VISA = "visa"
    MASTERCARD = "mastercard"
    VERVE = "verve"
    UNKNOWN = "unknown"


class PaymentIntentStatus(str, enum.Enum):
    REQUIRES_PAYMENT_METHOD = "requires_payment_method"
    REQUIRES_CONFIRMATION = "requires_confirmation"
    PROCESSING = "processing"
    SUCCEEDED = "succeeded"
    DECLINED = "declined"
    CANCELED = "canceled"


class PaymentMethod(Base):
    __tablename__ = "payment_methods"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    merchant_id = Column(UUID(as_uuid=True), ForeignKey("merchants.id"), nullable=False, index=True)
    customer_id = Column(UUID(as_uuid=True), ForeignKey("customers.id"), nullable=True, index=True)

    type = Column(Enum(PaymentMethodType), nullable=False, default=PaymentMethodType.CARD)

    # We NEVER store a raw PAN. "token" is an opaque reference generated by our simulator's tokenize step.
    # last4 and brand are safe, non-sensitive display data derived at tokenization time.
    token = Column(String(255), unique=True, nullable=False, index=True)
    card_brand = Column(Enum(CardBrand), nullable=False, default=CardBrand.UNKNOWN)
    card_last4 = Column(String(4), nullable=False)
    card_exp_month = Column(Integer, nullable=False)
    card_exp_year = Column(Integer, nullable=False)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)


class PaymentIntent(Base):
    __tablename__ = "payment_intents"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    merchant_id = Column(UUID(as_uuid=True), ForeignKey("merchants.id"), nullable=False, index=True)
    customer_id = Column(UUID(as_uuid=True), ForeignKey("customers.id"), nullable=True, index=True)
    payment_method_id = Column(UUID(as_uuid=True), ForeignKey("payment_methods.id"), nullable=True)

    # Stored in the smallest currency unit (cents) to avoid float rounding errors — 150000 = KES 1,500.00
    amount_minor = Column(Integer, nullable=False)
    currency = Column(String(3), nullable=False)

    status = Column(Enum(PaymentIntentStatus), nullable=False, default=PaymentIntentStatus.REQUIRES_PAYMENT_METHOD)

    description = Column(String(500), nullable=True)
    failure_reason = Column(String(255), nullable=True)

    # Idempotency: merchant-supplied key prevents duplicate intents from network retries
    idempotency_key = Column(String(255), nullable=True, index=True)

    is_live_mode = Column(String(10), nullable=False, default="test")  # "test" or "live"

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    payment_method = relationship("PaymentMethod")