"""add ledger_entries and wallet_balances

Revision ID: 13d1191d605d
Revises: a89ff3cbfab7
Create Date: 2026-07-15 21:42:27.365686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13d1191d605d'
down_revision: Union[str, None] = 'a89ff3cbfab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_group_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Enum('PLATFORM_CASH', 'MERCHANT_PAYABLE', 'PLATFORM_REVENUE', name='ledgeraccounttype'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='ledgerentrydirection'), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entry_type', sa.Enum('PAYMENT_SETTLEMENT', 'REFUND', 'PAYOUT', 'ADJUSTMENT', name='ledgerentrytype'), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_merchant_id'), 'ledger_entries', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_reference_id'), 'ledger_entries', ['reference_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_group_id'), 'ledger_entries', ['transaction_group_id'], unique=False)
    op.create_table('wallet_balances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('available_balance_minor', sa.Integer(), nullable=False),
    sa.Column('total_settled_minor', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_balances_merchant_id'), 'wallet_balances', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_balances_merchant_id'), table_name='wallet_balances')
    op.drop_table('wallet_balances')
    op.drop_index(op.f('ix_ledger_entries_transaction_group_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_reference_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_merchant_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    # ### end Alembic commands ###
