"""add notifications table

Revision ID: 2444ed624b1e
Revises: 45d13f6babac
Create Date: 2026-07-16 23:05:36.165522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2444ed624b1e'
down_revision: Union[str, None] = '45d13f6babac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('EMAIL', 'SMS', name='notificationchannel'), nullable=False),
    sa.Column('notification_type', sa.Enum('PAYMENT_RECEIPT', 'PAYMENT_DECLINED', 'REFUND_CONFIRMATION', 'PAYOUT_PAID', name='notificationtype'), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='notificationstatus'), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_customer_id'), 'notifications', ['customer_id'], unique=False)
    op.create_index(op.f('ix_notifications_merchant_id'), 'notifications', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_merchant_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_customer_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
