"""expand merchants table, add api_keys
Revision ID: 2bd1cb1d4eba
Revises: 35e929d6f060
Create Date: 2026-07-15 17:01:12.816976
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2bd1cb1d4eba'
down_revision: Union[str, None] = '35e929d6f060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('key_type', sa.Enum('TEST_PUBLIC', 'TEST_SECRET', 'LIVE_PUBLIC', 'LIVE_SECRET', name='apikeytype'), nullable=False),
    sa.Column('display_prefix', sa.String(length=20), nullable=False),
    sa.Column('hashed_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_merchant_id'), 'api_keys', ['merchant_id'], unique=False)
    op.add_column('merchants', sa.Column('business_email', sa.String(length=255), nullable=False, server_default='unknown@example.com'))
    op.add_column('merchants', sa.Column('country', sa.String(length=2), nullable=False, server_default='KE'))
    op.add_column('merchants', sa.Column('default_currency', sa.String(length=3), nullable=False, server_default='KES'))

    # add_column doesn't auto-create Postgres enum types the way create_table does — create it explicitly first
    kyc_status_enum = sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='kycstatus')
    kyc_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('merchants', sa.Column('kyc_status', kyc_status_enum, nullable=False, server_default='PENDING'))

    op.add_column('merchants', sa.Column('kyc_rejection_reason', sa.String(length=500), nullable=True))
    op.add_column('merchants', sa.Column('settlement_bank_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('settlement_account_number', sa.String(length=64), nullable=True))
    op.add_column('merchants', sa.Column('settlement_account_name', sa.String(length=255), nullable=True))
    op.add_column('merchants', sa.Column('is_live_mode_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('merchants', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # Drop the temporary server_defaults — SQLAlchemy's model doesn't declare them at the Python level
    # (except updated_at, which legitimately keeps its server_default), so remove the rest to match the model exactly.
    op.alter_column('merchants', 'business_email', server_default=None)
    op.alter_column('merchants', 'country', server_default='KE')
    op.alter_column('merchants', 'default_currency', server_default='KES')
    op.alter_column('merchants', 'kyc_status', server_default=None)
    op.alter_column('merchants', 'is_live_mode_enabled', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'updated_at')
    op.drop_column('merchants', 'is_live_mode_enabled')
    op.drop_column('merchants', 'settlement_account_name')
    op.drop_column('merchants', 'settlement_account_number')
    op.drop_column('merchants', 'settlement_bank_name')
    op.drop_column('merchants', 'kyc_rejection_reason')
    op.drop_column('merchants', 'kyc_status')

    kyc_status_enum = sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='kycstatus')
    kyc_status_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_column('merchants', 'default_currency')
    op.drop_column('merchants', 'country')
    op.drop_column('merchants', 'business_email')
    op.drop_index(op.f('ix_api_keys_merchant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###