"""add customers table and link payment_intents/payment_methods to customers

Revision ID: 498a86e96eb9
Revises: a9550768e4a9
Create Date: 2026-07-16 15:16:54.690815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498a86e96eb9'
down_revision: Union[str, None] = 'a9550768e4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'email', name='uq_customers_merchant_email')
    )
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.add_column('payment_intents', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payment_intents_customer_id'), 'payment_intents', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'payment_intents', 'customers', ['customer_id'], ['id'])
    op.add_column('payment_methods', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payment_methods_customer_id'), 'payment_methods', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'payment_methods', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_methods', type_='foreignkey')
    op.drop_index(op.f('ix_payment_methods_customer_id'), table_name='payment_methods')
    op.drop_column('payment_methods', 'customer_id')
    op.drop_constraint(None, 'payment_intents', type_='foreignkey')
    op.drop_index(op.f('ix_payment_intents_customer_id'), table_name='payment_intents')
    op.drop_column('payment_intents', 'customer_id')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
