"""add client_secret to payment_intents

Revision ID: 9098ed2aa9c4
Revises: 4a85f97705c5
Create Date: 2026-07-21 16:24:50.122714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9098ed2aa9c4'
down_revision: Union[str, None] = '4a85f97705c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_intents', sa.Column('client_secret', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payment_intents', ['client_secret'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_intents', type_='unique')
    op.drop_column('payment_intents', 'client_secret')
    # ### end Alembic commands ###
