"""add fraud detection tables

Revision ID: a1a3d0dd2807
Revises: 2444ed624b1e
Create Date: 2026-07-16 23:44:40.895818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1a3d0dd2807'
down_revision: Union[str, None] = '2444ed624b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('card_fingerprint', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_cards_card_fingerprint'), 'blacklisted_cards', ['card_fingerprint'], unique=False)
    op.create_index(op.f('ix_blacklisted_cards_merchant_id'), 'blacklisted_cards', ['merchant_id'], unique=False)
    op.create_table('blacklisted_ips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blacklisted_ips_ip_address'), 'blacklisted_ips', ['ip_address'], unique=False)
    op.create_index(op.f('ix_blacklisted_ips_merchant_id'), 'blacklisted_ips', ['merchant_id'], unique=False)
    op.create_table('fraud_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='fraudcasestatus'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_cases_merchant_id'), 'fraud_cases', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_fraud_cases_payment_intent_id'), 'fraud_cases', ['payment_intent_id'], unique=True)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('device_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_merchant_id'), 'risk_assessments', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_payment_intent_id'), 'risk_assessments', ['payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_assessments_payment_intent_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_merchant_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_fraud_cases_payment_intent_id'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_merchant_id'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    op.drop_index(op.f('ix_blacklisted_ips_merchant_id'), table_name='blacklisted_ips')
    op.drop_index(op.f('ix_blacklisted_ips_ip_address'), table_name='blacklisted_ips')
    op.drop_table('blacklisted_ips')
    op.drop_index(op.f('ix_blacklisted_cards_merchant_id'), table_name='blacklisted_cards')
    op.drop_index(op.f('ix_blacklisted_cards_card_fingerprint'), table_name='blacklisted_cards')
    op.drop_table('blacklisted_cards')
    # ### end Alembic commands ###
