"""add payment_methods and payment_intents

Revision ID: a89ff3cbfab7
Revises: 2bd1cb1d4eba
Create Date: 2026-07-15 21:00:00.723420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a89ff3cbfab7'
down_revision: Union[str, None] = '2bd1cb1d4eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CARD', name='paymentmethodtype'), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('card_brand', sa.Enum('VISA', 'MASTERCARD', 'VERVE', 'UNKNOWN', name='cardbrand'), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('card_exp_month', sa.Integer(), nullable=False),
    sa.Column('card_exp_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_merchant_id'), 'payment_methods', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_methods_token'), 'payment_methods', ['token'], unique=True)
    op.create_table('payment_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('payment_method_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('REQUIRES_PAYMENT_METHOD', 'REQUIRES_CONFIRMATION', 'PROCESSING', 'SUCCEEDED', 'DECLINED', 'CANCELED', name='paymentintentstatus'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('is_live_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_intents_idempotency_key'), 'payment_intents', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_payment_intents_merchant_id'), 'payment_intents', ['merchant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_intents_merchant_id'), table_name='payment_intents')
    op.drop_index(op.f('ix_payment_intents_idempotency_key'), table_name='payment_intents')
    op.drop_table('payment_intents')
    op.drop_index(op.f('ix_payment_methods_token'), table_name='payment_methods')
    op.drop_index(op.f('ix_payment_methods_merchant_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    # ### end Alembic commands ###
