"""add refunds table

Revision ID: a9550768e4a9
Revises: 3adda26ebfa5
Create Date: 2026-07-16 14:48:41.642115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9550768e4a9'
down_revision: Union[str, None] = '3adda26ebfa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_intent_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='refundstatus'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('ledger_transaction_group_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_intent_id'], ['payment_intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_merchant_id'), 'refunds', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_refunds_payment_intent_id'), 'refunds', ['payment_intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_payment_intent_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_merchant_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
